<?php

use FHV\Bundle\TmdBundle\DecisionTree\Model\Result;
use FHV\Bundle\TmdBundle\DecisionTree\Model\Decision;
use FHV\Bundle\TmdBundle\DecisionTree\Model\Node;
use FHV\Bundle\TmdBundle\DecisionTree\Model\Tree;
use FHV\Bundle\TmdBundle\Model\Feature;
use FHV\Bundle\TmdBundle\DecisionTree\DecisionTreeInterface;

/**
 * DO NOT EDIT - This class is autogenerated by the the decission tree manager
 * Class GISDecisionTree
 * @package FHV\Bundle\TmdBundle\DecisionTree
 */
class GISDecisionTree implements DecisionTreeInterface
{
    protected $tree;

    function __construct()
    {
                    $node0 = new Node();
                    $node0->setDecision(new Decision('meanvelocity', '>', 2.044));
                                    $node1 = new Node();
                    $node1->setDecision(new Decision('meanvelocity', '>', 7.887));
                                    $node2 = new Node();
                    $node2->setDecision(new Decision('railcloseness', '>', 0.011));
                                    $node3 = new Node();
                            $node3->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 6,
                        ]));
                            $node4 = new Node();
                    $node4->setDecision(new Decision('ptscloseness', '>', 1.5));
                                    $node5 = new Node();
                    $node5->setDecision(new Decision('ptscloseness', '>', 4.5));
                                    $node6 = new Node();
                    $node6->setDecision(new Decision('railcloseness', '>', 0));
                                    $node7 = new Node();
                            $node7->setResult(new Result([
                            'bike' => 0,
                            'drive' => 1,
                            'walk' => 0,
                            'bus' => 1,
                            'train' => 0,
                        ]));
                            $node8 = new Node();
                            $node8->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 2,
                            'train' => 0,
                        ]));
                            $node9 = new Node();
                            $node9->setResult(new Result([
                            'bus' => 2,
                            'drive' => 12,
                            'walk' => 0,
                            'bike' => 0,
                            'train' => 0,
                        ]));
                            $node10 = new Node();
                            $node10->setResult(new Result([
                            'bike' => 0,
                            'drive' => 48,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node11 = new Node();
                    $node11->setDecision(new Decision('ptscloseness', '>', 2.5));
                                    $node12 = new Node();
                    $node12->setDecision(new Decision('meanvelocity', '>', 6.368));
                                    $node13 = new Node();
                    $node13->setDecision(new Decision('highwaycloseness', '>', 0));
                                    $node14 = new Node();
                            $node14->setResult(new Result([
                            'bike' => 2,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node15 = new Node();
                            $node15->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 9,
                            'train' => 0,
                        ]));
                            $node16 = new Node();
                            $node16->setResult(new Result([
                            'bike' => 9,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node17 = new Node();
                            $node17->setResult(new Result([
                            'bike' => 17,
                            'drive' => 11,
                            'walk' => 0,
                            'bus' => 1,
                            'train' => 0,
                        ]));
                            $node18 = new Node();
                    $node18->setDecision(new Decision('maxacceleration', '>', 1.993));
                                    $node19 = new Node();
                    $node19->setDecision(new Decision('stoprate', '>', 0.126));
                                    $node20 = new Node();
                            $node20->setResult(new Result([
                            'bike' => 2,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node21 = new Node();
                    $node21->setDecision(new Decision('maxvelocity', '>', 44.538));
                                    $node22 = new Node();
                            $node22->setResult(new Result([
                            'bike' => 2,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node23 = new Node();
                    $node23->setDecision(new Decision('meanacceleration', '>', 0.476));
                                    $node24 = new Node();
                    $node24->setDecision(new Decision('maxacceleration', '>', 3.211));
                                    $node25 = new Node();
                            $node25->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 6,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node26 = new Node();
                    $node26->setDecision(new Decision('maxvelocity', '>', 5.613));
                                    $node27 = new Node();
                            $node27->setResult(new Result([
                            'bike' => 2,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node28 = new Node();
                            $node28->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 2,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node29 = new Node();
                            $node29->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 14,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node30 = new Node();
                            $node30->setResult(new Result([
                            'bus' => 0,
                            'drive' => 1,
                            'walk' => 31,
                            'bike' => 0,
                            'train' => 0,
                        ]));
                
                                    $node0->setLeft($node1);
                            $node0->setRight($node18);
                                    $node1->setParent($node0);
                            $node1->setLeft($node2);
                            $node1->setRight($node11);
                                    $node2->setParent($node1);
                            $node2->setLeft($node3);
                            $node2->setRight($node4);
                                    $node3->setParent($node3);
                                                    $node4->setParent($node2);
                            $node4->setLeft($node5);
                            $node4->setRight($node10);
                                    $node5->setParent($node4);
                            $node5->setLeft($node6);
                            $node5->setRight($node9);
                                    $node6->setParent($node5);
                            $node6->setLeft($node7);
                            $node6->setRight($node8);
                                    $node7->setParent($node7);
                                                    $node8->setParent($node8);
                                                    $node9->setParent($node9);
                                                    $node10->setParent($node10);
                                                    $node11->setParent($node1);
                            $node11->setLeft($node12);
                            $node11->setRight($node17);
                                    $node12->setParent($node11);
                            $node12->setLeft($node13);
                            $node12->setRight($node16);
                                    $node13->setParent($node12);
                            $node13->setLeft($node14);
                            $node13->setRight($node15);
                                    $node14->setParent($node14);
                                                    $node15->setParent($node15);
                                                    $node16->setParent($node16);
                                                    $node17->setParent($node17);
                                                    $node18->setParent($node0);
                            $node18->setLeft($node19);
                            $node18->setRight($node30);
                                    $node19->setParent($node18);
                            $node19->setLeft($node20);
                            $node19->setRight($node21);
                                    $node20->setParent($node20);
                                                    $node21->setParent($node19);
                            $node21->setLeft($node22);
                            $node21->setRight($node23);
                                    $node22->setParent($node22);
                                                    $node23->setParent($node21);
                            $node23->setLeft($node24);
                            $node23->setRight($node29);
                                    $node24->setParent($node23);
                            $node24->setLeft($node25);
                            $node24->setRight($node26);
                                    $node25->setParent($node25);
                                                    $node26->setParent($node24);
                            $node26->setLeft($node27);
                            $node26->setRight($node28);
                                    $node27->setParent($node27);
                                                    $node28->setParent($node28);
                                                    $node29->setParent($node29);
                                                    $node30->setParent($node30);
                                
        $this->tree = new Tree($node0);
    }

    /**
    * Process values by tree
    *
    * @param array $values
    *
    * @return array
    */
    public function process(array $values)
    {
        return $this->tree->process($values);
    }
}
