<?php

use FHV\Bundle\TmdBundle\DecisionTree\Model\Result;
use FHV\Bundle\TmdBundle\DecisionTree\Model\Decision;
use FHV\Bundle\TmdBundle\DecisionTree\Model\Node;
use FHV\Bundle\TmdBundle\DecisionTree\Model\Tree;
use FHV\Bundle\TmdBundle\Model\Feature;
use FHV\Bundle\TmdBundle\DecisionTree\DecisionTreeInterface;

/**
 * DO NOT EDIT - This class is autogenerated by the the decission tree manager
 * Class GISDecisionTree
 * @package FHV\Bundle\TmdBundle\DecisionTree
 */
class GISDecisionTree implements DecisionTreeInterface
{
    protected $tree;

    function __construct()
    {
                    $node0 = new Node();
                    $node0->setDecision(new Decision('meanvelocity', '>', 2.041));
                                    $node1 = new Node();
                    $node1->setDecision(new Decision('railcloseness', '>', 0.003));
                                    $node2 = new Node();
                            $node2->setResult(new Result([
                            'bike' => 1,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 8,
                        ]));
                            $node3 = new Node();
                    $node3->setDecision(new Decision('ptscloseness', '>', 0.528));
                                    $node4 = new Node();
                            $node4->setResult(new Result([
                            'bike' => 1,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 8,
                            'train' => 0,
                        ]));
                            $node5 = new Node();
                    $node5->setDecision(new Decision('meanvelocity', '>', 7.599));
                                    $node6 = new Node();
                    $node6->setDecision(new Decision('meanvelocity', '>', 7.922));
                                    $node7 = new Node();
                    $node7->setDecision(new Decision('ptscloseness', '>', 0.171));
                                    $node8 = new Node();
                    $node8->setDecision(new Decision('stoprate', '>', 0.002));
                                    $node9 = new Node();
                            $node9->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 2,
                            'train' => 0,
                        ]));
                            $node10 = new Node();
                            $node10->setResult(new Result([
                            'bus' => 1,
                            'drive' => 5,
                            'walk' => 0,
                            'bike' => 0,
                            'train' => 0,
                        ]));
                            $node11 = new Node();
                            $node11->setResult(new Result([
                            'bike' => 0,
                            'drive' => 56,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node12 = new Node();
                            $node12->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 2,
                            'train' => 0,
                        ]));
                            $node13 = new Node();
                    $node13->setDecision(new Decision('ptscloseness', '>', 0.25));
                                    $node14 = new Node();
                            $node14->setResult(new Result([
                            'bike' => 1,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 1,
                            'train' => 0,
                        ]));
                            $node15 = new Node();
                    $node15->setDecision(new Decision('meanacceleration', '>', 0.981));
                                    $node16 = new Node();
                    $node16->setDecision(new Decision('maxacceleration', '>', 2.403));
                                    $node17 = new Node();
                    $node17->setDecision(new Decision('maxvelocity', '>', 11.427));
                                    $node18 = new Node();
                    $node18->setDecision(new Decision('maxvelocity', '>', 11.623));
                                    $node19 = new Node();
                    $node19->setDecision(new Decision('railcloseness', '>', 0));
                                    $node20 = new Node();
                            $node20->setResult(new Result([
                            'bike' => 5,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node21 = new Node();
                    $node21->setDecision(new Decision('maxacceleration', '>', 15.284));
                                    $node22 = new Node();
                            $node22->setResult(new Result([
                            'bike' => 0,
                            'drive' => 2,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node23 = new Node();
                    $node23->setDecision(new Decision('maxvelocity', '>', 16.38));
                                    $node24 = new Node();
                            $node24->setResult(new Result([
                            'bike' => 5,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node25 = new Node();
                    $node25->setDecision(new Decision('stoprate', '>', 0.002));
                                    $node26 = new Node();
                            $node26->setResult(new Result([
                            'bike' => 0,
                            'drive' => 3,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node27 = new Node();
                    $node27->setDecision(new Decision('meanvelocity', '>', 7.169));
                                    $node28 = new Node();
                            $node28->setResult(new Result([
                            'bike' => 1,
                            'drive' => 2,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node29 = new Node();
                            $node29->setResult(new Result([
                            'bike' => 3,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node30 = new Node();
                            $node30->setResult(new Result([
                            'bike' => 0,
                            'drive' => 2,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node31 = new Node();
                            $node31->setResult(new Result([
                            'bike' => 5,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node32 = new Node();
                            $node32->setResult(new Result([
                            'bike' => 0,
                            'drive' => 1,
                            'walk' => 0,
                            'bus' => 1,
                            'train' => 0,
                        ]));
                            $node33 = new Node();
                            $node33->setResult(new Result([
                            'bike' => 9,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node34 = new Node();
                    $node34->setDecision(new Decision('maxvelocity', '>', 47.534));
                                    $node35 = new Node();
                            $node35->setResult(new Result([
                            'bike' => 2,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node36 = new Node();
                    $node36->setDecision(new Decision('stoprate', '>', 0.136));
                                    $node37 = new Node();
                    $node37->setDecision(new Decision('stoprate', '>', 0.191));
                                    $node38 = new Node();
                            $node38->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 2,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node39 = new Node();
                            $node39->setResult(new Result([
                            'bike' => 2,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node40 = new Node();
                    $node40->setDecision(new Decision('meanvelocity', '>', 1.927));
                                    $node41 = new Node();
                            $node41->setResult(new Result([
                            'bike' => 1,
                            'drive' => 0,
                            'walk' => 1,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node42 = new Node();
                            $node42->setResult(new Result([
                            'bike' => 1,
                            'drive' => 1,
                            'walk' => 52,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                
                                    $node0->setLeft($node1);
                            $node0->setRight($node34);
                                    $node1->setParent($node0);
                            $node1->setLeft($node2);
                            $node1->setRight($node3);
                                    $node2->setParent($node2);
                                                    $node3->setParent($node1);
                            $node3->setLeft($node4);
                            $node3->setRight($node5);
                                    $node4->setParent($node4);
                                                    $node5->setParent($node3);
                            $node5->setLeft($node6);
                            $node5->setRight($node13);
                                    $node6->setParent($node5);
                            $node6->setLeft($node7);
                            $node6->setRight($node12);
                                    $node7->setParent($node6);
                            $node7->setLeft($node8);
                            $node7->setRight($node11);
                                    $node8->setParent($node7);
                            $node8->setLeft($node9);
                            $node8->setRight($node10);
                                    $node9->setParent($node9);
                                                    $node10->setParent($node10);
                                                    $node11->setParent($node11);
                                                    $node12->setParent($node12);
                                                    $node13->setParent($node5);
                            $node13->setLeft($node14);
                            $node13->setRight($node15);
                                    $node14->setParent($node14);
                                                    $node15->setParent($node13);
                            $node15->setLeft($node16);
                            $node15->setRight($node33);
                                    $node16->setParent($node15);
                            $node16->setLeft($node17);
                            $node16->setRight($node32);
                                    $node17->setParent($node16);
                            $node17->setLeft($node18);
                            $node17->setRight($node31);
                                    $node18->setParent($node17);
                            $node18->setLeft($node19);
                            $node18->setRight($node30);
                                    $node19->setParent($node18);
                            $node19->setLeft($node20);
                            $node19->setRight($node21);
                                    $node20->setParent($node20);
                                                    $node21->setParent($node19);
                            $node21->setLeft($node22);
                            $node21->setRight($node23);
                                    $node22->setParent($node22);
                                                    $node23->setParent($node21);
                            $node23->setLeft($node24);
                            $node23->setRight($node25);
                                    $node24->setParent($node24);
                                                    $node25->setParent($node23);
                            $node25->setLeft($node26);
                            $node25->setRight($node27);
                                    $node26->setParent($node26);
                                                    $node27->setParent($node25);
                            $node27->setLeft($node28);
                            $node27->setRight($node29);
                                    $node28->setParent($node28);
                                                    $node29->setParent($node29);
                                                    $node30->setParent($node30);
                                                    $node31->setParent($node31);
                                                    $node32->setParent($node32);
                                                    $node33->setParent($node33);
                                                    $node34->setParent($node0);
                            $node34->setLeft($node35);
                            $node34->setRight($node36);
                                    $node35->setParent($node35);
                                                    $node36->setParent($node34);
                            $node36->setLeft($node37);
                            $node36->setRight($node40);
                                    $node37->setParent($node36);
                            $node37->setLeft($node38);
                            $node37->setRight($node39);
                                    $node38->setParent($node38);
                                                    $node39->setParent($node39);
                                                    $node40->setParent($node36);
                            $node40->setLeft($node41);
                            $node40->setRight($node42);
                                    $node41->setParent($node41);
                                                    $node42->setParent($node42);
                                
        $this->tree = new Tree($node0);
    }

    /**
    * Process values by tree
    *
    * @param array $values
    *
    * @return array
    */
    public function process(array $values)
    {
        return $this->tree->process($values);
    }
}
