fhv_tmd_homepage:
    path:     /
    defaults: { _controller: FHVTmdBundle:Default:index }

fhv_tmd_foo:
    path:     /create/{name}
    defaults: { _controller: FHVTmdBundle:Default:foo, name: foo }

fhv_tmd_bar:
    path:     /analytics/{name}
    defaults: { _controller: FHVTmdBundle:Default:foo, name: bar }
