fhv_tmd_index:
    path:     /
    defaults: { _controller: FHVTmdBundle:Template:index }

fhv_tmd_create:
    path:     /create/{name}
    defaults: { _controller: FHVTmdBundle:Template:create, name: foo }

fhv_tmd_analytics:
    path:     /analytics/{name}
    defaults: { _controller: FHVTmdBundle:Template:analytics, name: bar }
