fhv_tmd_track:
    type:     rest
    resource: FHV\Bundle\TmdBundle\Controller\TrackController

fhv_tmd_result:
    type:     rest
    resource: FHV\Bundle\TmdBundle\Controller\ResultController

fhv_tmd_analyse:
    type:     rest
    resource: FHV\Bundle\TmdBundle\Controller\AnalyseController
