fhv_tmd_index:
    path:     /
    defaults: { _controller: FHVTmdBundle:Template:index }

fhv_tmd_create:
    path:     /create
    defaults: { _controller: FHVTmdBundle:Template:create }

fhv_tmd_results:
    path:     /analyse
    defaults: { _controller: FHVTmdBundle:Template:analyse }

