services:
    fhv_tmd.geoCalUtil:
        class: FHV\Bundle\TmdBundle\Util\GeoCalcUtil
        arguments: ["%tmd.earth_circumference%"]

    fhv_tmd.segmentManager:
        class: FHV\Bundle\TmdBundle\Manager\SegmentManager
        arguments: ["@fhv_tmd.geoCalUtil"]

    fhv_tmd.trainingDataManager:
        class: FHV\Bundle\TmdBundle\Manager\GPXTrainingDataManager
        arguments: ["@fhv_tmd.segmentManager"]
