services:

    ##############################
    # Util
    ##############################

    fhv_tmd.trackPointUtil:
        class: FHV\Bundle\TmdBundle\Util\TrackpointUtil
        arguments:
          - %tmd.planet_circumference%

    ##############################
    # Filter
    ##############################

    # TODO check if they should be reinstaniated for each "request"

    fhv_tmd.fileReaderFilter:
          class: FHV\Bundle\TmdBundle\Filter\FileReaderFilter
          arguments:
            - %tmd.filter.min_trackpoints_per_segment%
            - %tmd.gpx_namespace%

    fhv_tmd.trackPointFilter:
          class: FHV\Bundle\TmdBundle\Filter\TrackpointFilter
          arguments:
            - @fhv_tmd.trackPointUtil
            - %tmd.filter.max_distance%
            - %tmd.filter.min_distance%
            - %tmd.filter.max_altitude_change%
            - %tmd.filter.min_time_difference%
            - %tmd.filter.min_trackpoints_per_segment%
            - %tmd.filter.points_to_skip_from_start%
            - %tmd.filter.min_valid_points%

    fhv_tmd.segmentFilter:
          class: FHV\Bundle\TmdBundle\Filter\TracksegmentFilter
          arguments:
            - @fhv_tmd.trackPointUtil
            - %tmd.filter.min_trackpoints_per_segment%
            - %tmd.filter.max_velocity_for_nearly_stoppoints%
            - %tmd.filter.max_time_without_movement%

    fhv_tmd.fileWriterFilter:
          class: FHV\Bundle\TmdBundle\Filter\FileWriterFilter
          arguments: []

    fhv_tmd.segmentationFilter:
          class: FHV\Bundle\TmdBundle\Filter\SegmentationFilter
          arguments:
            - @doctrine.orm.entity_manager
            - @fhv_tmd.trackPointUtil
            - %tmd.segmentation.max_walk_velocity%
            - %tmd.segmentation.max_walk_acceleration%
            - %tmd.segmentation.min_segment_time%
            - %tmd.segmentation.min_segment_distance%
            - %tmd.segmentation.max_time_difference%
            - %tmd.segmentation.max_time_without_movement%
            - %tmd.segmentation.max_velocity_for_nearly_stoppoints%

    ##############################
    # Manager
    ##############################

    fhv_tmd.trainingDataManager:
        class: FHV\Bundle\TmdBundle\Manager\TrainingDataManager
        arguments:
          - @fhv_tmd.trackPointFilter
          - @fhv_tmd.fileReaderFilter
          - @fhv_tmd.fileWriterFilter
          - @fhv_tmd.segmentFilter

    fhv_tmd.trackManager:
        class: FHV\Bundle\TmdBundle\Manager\TrackManager
        arguments:
        - @doctrine.orm.entity_manager
        - @fhv_tmd.trackPointFilter
        - @fhv_tmd.fileReaderFilter
        - @fhv_tmd.segmentationFilter
        - @fhv_tmd.segmentFilter






