services:

    ##############################
    # Util
    ##############################

    fhv_tmd.trackPointUtil:
        class: FHV\Bundle\TmdBundle\Util\TrackpointUtil
        arguments:
          - %tmd.planet_circumference%

    ##############################
    # Filter
    ##############################

    fhv_tmd.fileReaderFilter:
          class: FHV\Bundle\TmdBundle\Filter\FileReaderFilter
          arguments:
            - %tmd.filter.min_trackpoints_per_segment%
            - %tmd.gpx_namespace%

    fhv_tmd.trackPointFilter:
          class: FHV\Bundle\TmdBundle\Filter\TrackpointFilter
          arguments:
            - @fhv_tmd.trackPointUtil
            - %tmd.filter.max_distance%
            - %tmd.filter.min_distance%
            - %tmd.filter.max_altitude_change%
            - %tmd.filter.min_time_difference%
            - %tmd.filter.min_trackpoints_per_segment%
            - %tmd.filter.points_to_skip_from_start%
            - %tmd.filter.min_valid_points%

    fhv_tmd.segmentFilter:
          class: FHV\Bundle\TmdBundle\Filter\TracksegmentFilter
          arguments:
            - @fhv_tmd.trackPointUtil
            - %tmd.filter.min_trackpoints_per_segment%
            - %tmd.filter.max_velocity_for_nearly_stoppoints%
            - %tmd.filter.max_time_without_movement%

    fhv_tmd.fileWriterFilter:
          class: FHV\Bundle\TmdBundle\Filter\FileWriterFilter
          arguments:
            - %tmd.analyse%

    fhv_tmd.segmentationFilter:
          class: FHV\Bundle\TmdBundle\Filter\SegmentationFilter
          arguments:
            - @fhv_tmd.trackPointUtil
            - %tmd.segmentation.max_walk_velocity%
            - %tmd.segmentation.max_walk_acceleration%
            - %tmd.segmentation.min_segment_time%
            - %tmd.segmentation.min_segment_distance%
            - %tmd.segmentation.max_time_difference%
            - %tmd.segmentation.max_time_without_movement%
            - %tmd.segmentation.max_velocity_for_nearly_stoppoints%

    fhv_tmd.travelModeFilter:
          class: FHV\Bundle\TmdBundle\Filter\TravelModeFilter
          arguments:
            - @fhv_tmd.decisionTreeManager

    fhv_tmd.postProcessFilter:
          class: FHV\Bundle\TmdBundle\Filter\PostprocessFilter
          arguments: []

    fhv_tmd.databaseFilter:
          class: FHV\Bundle\TmdBundle\Filter\DatabaseFilter
          arguments: []

    ##############################
    # Manager
    ##############################

    fhv_tmd.trainingDataManager:
        class: FHV\Bundle\TmdBundle\Manager\TrainingDataManager
        arguments:
          - @fhv_tmd.trackPointFilter
          - @fhv_tmd.fileReaderFilter
          - @fhv_tmd.fileWriterFilter
          - @fhv_tmd.segmentFilter

    fhv_tmd.trackManager:
        class: FHV\Bundle\TmdBundle\Manager\TrackManager
        arguments:
          - @doctrine.orm.entity_manager
          - @fhv_tmd.trackPointFilter
          - @fhv_tmd.fileReaderFilter
          - @fhv_tmd.segmentationFilter
          - @fhv_tmd.segmentFilter
          - @fhv_tmd.travelModeFilter
          - @fhv_tmd.postProcessFilter
          - @fhv_tmd.databaseFilter

    fhv_tmd.resultManager:
        class: FHV\Bundle\TmdBundle\Manager\ResultManager
        arguments:
          - @doctrine.orm.entity_manager

    fhv_tmd.analyseManager:
        class: FHV\Bundle\TmdBundle\Manager\AnalyseManager
        arguments:
          - @doctrine.orm.entity_manager
          - %tmd.analyse%

    fhv_tmd.decisionTreeManager:
        class: FHV\Bundle\TmdBundle\DecisionTree\Manager\DecisionTreeManager
        arguments:
          - %tmd.analyse%






