services:
    fhv_tmd.trackPointUtil:
        class: FHV\Bundle\TmdBundle\Util\TrackPointUtil
        arguments: ["%tmd.earth_circumference%"]

    fhv_tmd.segmentManager:
        class: FHV\Bundle\TmdBundle\Manager\SegmentManager
        arguments: ["@fhv_tmd.trackPointUtil"]

    fhv_tmd.trainingDataManager:
        class: FHV\Bundle\TmdBundle\Manager\TrainingDataManager
        arguments: ["@fhv_tmd.segmentManager"]
