<?php

use FHV\Bundle\TmdBundle\DecisionTree\Model\Result;
use FHV\Bundle\TmdBundle\DecisionTree\Model\Decision;
use FHV\Bundle\TmdBundle\DecisionTree\Model\Node;
use FHV\Bundle\TmdBundle\DecisionTree\Model\Tree;
use FHV\Bundle\TmdBundle\Model\Feature;
use FHV\Bundle\TmdBundle\DecisionTree\DecisionTreeInterface;

/**
 * DO NOT EDIT - This class is autogenerated by the the decission tree manager
 * Class BasicDecisionTree
 * @package FHV\Bundle\TmdBundle\DecisionTree
 */
class BasicDecisionTree implements DecisionTreeInterface
{
    protected $tree;

    function __construct()
    {
                    $node0 = new Node();
                    $node0->setDecision(new Decision('meanvelocity', '>', 2.044));
                                    $node1 = new Node();
                    $node1->setDecision(new Decision('meanvelocity', '>', 7.887));
                                    $node2 = new Node();
                    $node2->setDecision(new Decision('meanvelocity', '>', 20.939));
                                    $node3 = new Node();
                            $node3->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 5,
                        ]));
                            $node4 = new Node();
                    $node4->setDecision(new Decision('meanacceleration', '>', 4.365));
                                    $node5 = new Node();
                    $node5->setDecision(new Decision('stoprate', '>', 0));
                                    $node6 = new Node();
                    $node6->setDecision(new Decision('meanvelocity', '>', 17.756));
                                    $node7 = new Node();
                            $node7->setResult(new Result([
                            'bike' => 0,
                            'drive' => 3,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node8 = new Node();
                            $node8->setResult(new Result([
                            'bike' => 0,
                            'drive' => 1,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 3,
                        ]));
                            $node9 = new Node();
                            $node9->setResult(new Result([
                            'bike' => 0,
                            'drive' => 13,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node10 = new Node();
                    $node10->setDecision(new Decision('stoprate', '>', 0));
                                    $node11 = new Node();
                    $node11->setDecision(new Decision('stoprate', '>', 0.001));
                                    $node12 = new Node();
                    $node12->setDecision(new Decision('meanvelocity', '>', 8.475));
                                    $node13 = new Node();
                            $node13->setResult(new Result([
                            'bike' => 0,
                            'drive' => 18,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node14 = new Node();
                    $node14->setDecision(new Decision('stoprate', '>', 0.002));
                                    $node15 = new Node();
                    $node15->setDecision(new Decision('stoprate', '>', 0.003));
                                    $node16 = new Node();
                            $node16->setResult(new Result([
                            'bike' => 0,
                            'drive' => 1,
                            'walk' => 0,
                            'bus' => 1,
                            'train' => 0,
                        ]));
                            $node17 = new Node();
                            $node17->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 2,
                            'train' => 0,
                        ]));
                            $node18 = new Node();
                            $node18->setResult(new Result([
                            'bike' => 0,
                            'drive' => 2,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node19 = new Node();
                            $node19->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 2,
                            'train' => 0,
                        ]));
                            $node20 = new Node();
                            $node20->setResult(new Result([
                            'bike' => 0,
                            'drive' => 23,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node21 = new Node();
                    $node21->setDecision(new Decision('meanvelocity', '>', 6.12));
                                    $node22 = new Node();
                    $node22->setDecision(new Decision('stoprate', '>', 0));
                                    $node23 = new Node();
                    $node23->setDecision(new Decision('maxvelocity', '>', 12.081));
                                    $node24 = new Node();
                            $node24->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 9,
                            'train' => 0,
                        ]));
                            $node25 = new Node();
                    $node25->setDecision(new Decision('stoprate', '>', 0.001));
                                    $node26 = new Node();
                            $node26->setResult(new Result([
                            'bike' => 0,
                            'drive' => 2,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node27 = new Node();
                            $node27->setResult(new Result([
                            'bike' => 1,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 1,
                            'train' => 0,
                        ]));
                            $node28 = new Node();
                            $node28->setResult(new Result([
                            'bus' => 0,
                            'drive' => 1,
                            'walk' => 0,
                            'bike' => 8,
                            'train' => 0,
                        ]));
                            $node29 = new Node();
                    $node29->setDecision(new Decision('stoprate', '>', 0.002));
                                    $node30 = new Node();
                    $node30->setDecision(new Decision('maxvelocity', '>', 10.906));
                                    $node31 = new Node();
                    $node31->setDecision(new Decision('meanvelocity', '>', 4.709));
                                    $node32 = new Node();
                            $node32->setResult(new Result([
                            'bike' => 2,
                            'drive' => 1,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node33 = new Node();
                            $node33->setResult(new Result([
                            'bike' => 0,
                            'drive' => 5,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node34 = new Node();
                            $node34->setResult(new Result([
                            'bike' => 6,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node35 = new Node();
                    $node35->setDecision(new Decision('stoprate', '>', 0));
                                    $node36 = new Node();
                            $node36->setResult(new Result([
                            'bike' => 16,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node37 = new Node();
                    $node37->setDecision(new Decision('maxacceleration', '>', 2.95));
                                    $node38 = new Node();
                            $node38->setResult(new Result([
                            'bike' => 2,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node39 = new Node();
                            $node39->setResult(new Result([
                            'bike' => 0,
                            'drive' => 2,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node40 = new Node();
                    $node40->setDecision(new Decision('maxacceleration', '>', 1.993));
                                    $node41 = new Node();
                    $node41->setDecision(new Decision('stoprate', '>', 0.126));
                                    $node42 = new Node();
                            $node42->setResult(new Result([
                            'bike' => 2,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node43 = new Node();
                    $node43->setDecision(new Decision('maxvelocity', '>', 44.538));
                                    $node44 = new Node();
                            $node44->setResult(new Result([
                            'bike' => 2,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node45 = new Node();
                    $node45->setDecision(new Decision('meanacceleration', '>', 0.476));
                                    $node46 = new Node();
                    $node46->setDecision(new Decision('maxacceleration', '>', 3.211));
                                    $node47 = new Node();
                            $node47->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 6,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node48 = new Node();
                    $node48->setDecision(new Decision('maxvelocity', '>', 5.613));
                                    $node49 = new Node();
                            $node49->setResult(new Result([
                            'bike' => 2,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node50 = new Node();
                            $node50->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 2,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node51 = new Node();
                            $node51->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 14,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node52 = new Node();
                            $node52->setResult(new Result([
                            'bus' => 0,
                            'drive' => 1,
                            'walk' => 31,
                            'bike' => 0,
                            'train' => 0,
                        ]));
                
                                    $node0->setLeft($node1);
                            $node0->setRight($node40);
                                    $node1->setParent($node0);
                            $node1->setLeft($node2);
                            $node1->setRight($node21);
                                    $node2->setParent($node1);
                            $node2->setLeft($node3);
                            $node2->setRight($node4);
                                    $node3->setParent($node3);
                                                    $node4->setParent($node2);
                            $node4->setLeft($node5);
                            $node4->setRight($node10);
                                    $node5->setParent($node4);
                            $node5->setLeft($node6);
                            $node5->setRight($node9);
                                    $node6->setParent($node5);
                            $node6->setLeft($node7);
                            $node6->setRight($node8);
                                    $node7->setParent($node7);
                                                    $node8->setParent($node8);
                                                    $node9->setParent($node9);
                                                    $node10->setParent($node4);
                            $node10->setLeft($node11);
                            $node10->setRight($node20);
                                    $node11->setParent($node10);
                            $node11->setLeft($node12);
                            $node11->setRight($node19);
                                    $node12->setParent($node11);
                            $node12->setLeft($node13);
                            $node12->setRight($node14);
                                    $node13->setParent($node13);
                                                    $node14->setParent($node12);
                            $node14->setLeft($node15);
                            $node14->setRight($node18);
                                    $node15->setParent($node14);
                            $node15->setLeft($node16);
                            $node15->setRight($node17);
                                    $node16->setParent($node16);
                                                    $node17->setParent($node17);
                                                    $node18->setParent($node18);
                                                    $node19->setParent($node19);
                                                    $node20->setParent($node20);
                                                    $node21->setParent($node1);
                            $node21->setLeft($node22);
                            $node21->setRight($node29);
                                    $node22->setParent($node21);
                            $node22->setLeft($node23);
                            $node22->setRight($node28);
                                    $node23->setParent($node22);
                            $node23->setLeft($node24);
                            $node23->setRight($node25);
                                    $node24->setParent($node24);
                                                    $node25->setParent($node23);
                            $node25->setLeft($node26);
                            $node25->setRight($node27);
                                    $node26->setParent($node26);
                                                    $node27->setParent($node27);
                                                    $node28->setParent($node28);
                                                    $node29->setParent($node21);
                            $node29->setLeft($node30);
                            $node29->setRight($node35);
                                    $node30->setParent($node29);
                            $node30->setLeft($node31);
                            $node30->setRight($node34);
                                    $node31->setParent($node30);
                            $node31->setLeft($node32);
                            $node31->setRight($node33);
                                    $node32->setParent($node32);
                                                    $node33->setParent($node33);
                                                    $node34->setParent($node34);
                                                    $node35->setParent($node29);
                            $node35->setLeft($node36);
                            $node35->setRight($node37);
                                    $node36->setParent($node36);
                                                    $node37->setParent($node35);
                            $node37->setLeft($node38);
                            $node37->setRight($node39);
                                    $node38->setParent($node38);
                                                    $node39->setParent($node39);
                                                    $node40->setParent($node0);
                            $node40->setLeft($node41);
                            $node40->setRight($node52);
                                    $node41->setParent($node40);
                            $node41->setLeft($node42);
                            $node41->setRight($node43);
                                    $node42->setParent($node42);
                                                    $node43->setParent($node41);
                            $node43->setLeft($node44);
                            $node43->setRight($node45);
                                    $node44->setParent($node44);
                                                    $node45->setParent($node43);
                            $node45->setLeft($node46);
                            $node45->setRight($node51);
                                    $node46->setParent($node45);
                            $node46->setLeft($node47);
                            $node46->setRight($node48);
                                    $node47->setParent($node47);
                                                    $node48->setParent($node46);
                            $node48->setLeft($node49);
                            $node48->setRight($node50);
                                    $node49->setParent($node49);
                                                    $node50->setParent($node50);
                                                    $node51->setParent($node51);
                                                    $node52->setParent($node52);
                                
        $this->tree = new Tree($node0);
    }

    /**
    * Process values by tree
    *
    * @param array $values
    *
    * @return array
    */
    public function process(array $values)
    {
        return $this->tree->process($values);
    }
}
