<?php

use FHV\Bundle\TmdBundle\DecisionTree\Model\Result;
use FHV\Bundle\TmdBundle\DecisionTree\Model\Decision;
use FHV\Bundle\TmdBundle\DecisionTree\Model\Node;
use FHV\Bundle\TmdBundle\DecisionTree\Model\Tree;
use FHV\Bundle\TmdBundle\Model\Feature;
use FHV\Bundle\TmdBundle\DecisionTree\DecisionTreeInterface;

/**
 * DO NOT EDIT - This class is autogenerated by the the decission tree manager
 * Class BasicDecisionTree
 * @package FHV\Bundle\TmdBundle\DecisionTree
 */
class BasicDecisionTree implements DecisionTreeInterface
{
    protected $tree;

    function __construct()
    {
                    $node0 = new Node();
                    $node0->setDecision(new Decision('meanvelocity', '>', 2.044));
                                    $node1 = new Node();
                    $node1->setDecision(new Decision('meanvelocity', '>', 20.939));
                                    $node2 = new Node();
                            $node2->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 4,
                        ]));
                            $node3 = new Node();
                    $node3->setDecision(new Decision('meanvelocity', '>', 7.887));
                                    $node4 = new Node();
                    $node4->setDecision(new Decision('meanvelocity', '>', 8.475));
                                    $node5 = new Node();
                    $node5->setDecision(new Decision('maxacceleration', '>', 13.35));
                                    $node6 = new Node();
                    $node6->setDecision(new Decision('maxvelocity', '>', 34.431));
                                    $node7 = new Node();
                            $node7->setResult(new Result([
                            'bike' => 0,
                            'drive' => 7,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node8 = new Node();
                    $node8->setDecision(new Decision('meanvelocity', '>', 17.27));
                                    $node9 = new Node();
                            $node9->setResult(new Result([
                            'bike' => 0,
                            'drive' => 2,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node10 = new Node();
                            $node10->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 2,
                        ]));
                            $node11 = new Node();
                            $node11->setResult(new Result([
                            'bike' => 0,
                            'drive' => 47,
                            'walk' => 0,
                            'bus' => 2,
                            'train' => 0,
                        ]));
                            $node12 = new Node();
                    $node12->setDecision(new Decision('meanvelocity', '>', 8.461));
                                    $node13 = new Node();
                            $node13->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 2,
                            'train' => 0,
                        ]));
                            $node14 = new Node();
                            $node14->setResult(new Result([
                            'bus' => 1,
                            'drive' => 5,
                            'walk' => 0,
                            'bike' => 0,
                            'train' => 0,
                        ]));
                            $node15 = new Node();
                    $node15->setDecision(new Decision('meanvelocity', '>', 7.594));
                                    $node16 = new Node();
                            $node16->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 4,
                            'train' => 0,
                        ]));
                            $node17 = new Node();
                    $node17->setDecision(new Decision('meanvelocity', '>', 6.12));
                                    $node18 = new Node();
                    $node18->setDecision(new Decision('stoprate', '>', 0.001));
                                    $node19 = new Node();
                    $node19->setDecision(new Decision('maxvelocity', '>', 12.327));
                                    $node20 = new Node();
                            $node20->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 5,
                            'train' => 0,
                        ]));
                            $node21 = new Node();
                            $node21->setResult(new Result([
                            'bike' => 0,
                            'drive' => 2,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node22 = new Node();
                    $node22->setDecision(new Decision('maxacceleration', '>', 4.329));
                                    $node23 = new Node();
                            $node23->setResult(new Result([
                            'bike' => 7,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node24 = new Node();
                            $node24->setResult(new Result([
                            'bike' => 0,
                            'drive' => 1,
                            'walk' => 0,
                            'bus' => 1,
                            'train' => 0,
                        ]));
                            $node25 = new Node();
                    $node25->setDecision(new Decision('meanacceleration', '>', 0.866));
                                    $node26 = new Node();
                    $node26->setDecision(new Decision('maxacceleration', '>', 2.31));
                                    $node27 = new Node();
                    $node27->setDecision(new Decision('stoprate', '>', 0.002));
                                    $node28 = new Node();
                    $node28->setDecision(new Decision('maxvelocity', '>', 10.906));
                                    $node29 = new Node();
                    $node29->setDecision(new Decision('meanvelocity', '>', 4.709));
                                    $node30 = new Node();
                            $node30->setResult(new Result([
                            'bike' => 2,
                            'drive' => 1,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node31 = new Node();
                            $node31->setResult(new Result([
                            'bike' => 0,
                            'drive' => 5,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node32 = new Node();
                            $node32->setResult(new Result([
                            'bike' => 4,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node33 = new Node();
                            $node33->setResult(new Result([
                            'bike' => 8,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node34 = new Node();
                            $node34->setResult(new Result([
                            'bike' => 0,
                            'drive' => 2,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node35 = new Node();
                            $node35->setResult(new Result([
                            'bike' => 7,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node36 = new Node();
                    $node36->setDecision(new Decision('maxvelocity', '>', 44.538));
                                    $node37 = new Node();
                            $node37->setResult(new Result([
                            'bike' => 2,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node38 = new Node();
                    $node38->setDecision(new Decision('stoprate', '>', 0.129));
                                    $node39 = new Node();
                    $node39->setDecision(new Decision('stoprate', '>', 0.166));
                                    $node40 = new Node();
                            $node40->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 2,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node41 = new Node();
                            $node41->setResult(new Result([
                            'bike' => 2,
                            'drive' => 0,
                            'walk' => 0,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node42 = new Node();
                    $node42->setDecision(new Decision('meanvelocity', '>', 1.947));
                                    $node43 = new Node();
                            $node43->setResult(new Result([
                            'bike' => 1,
                            'drive' => 0,
                            'walk' => 1,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node44 = new Node();
                    $node44->setDecision(new Decision('stoprate', '>', 0.094));
                                    $node45 = new Node();
                    $node45->setDecision(new Decision('meanacceleration', '>', 0.294));
                                    $node46 = new Node();
                            $node46->setResult(new Result([
                            'bike' => 0,
                            'drive' => 1,
                            'walk' => 1,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node47 = new Node();
                            $node47->setResult(new Result([
                            'bike' => 0,
                            'drive' => 0,
                            'walk' => 5,
                            'bus' => 0,
                            'train' => 0,
                        ]));
                            $node48 = new Node();
                            $node48->setResult(new Result([
                            'bus' => 0,
                            'drive' => 0,
                            'walk' => 44,
                            'bike' => 1,
                            'train' => 0,
                        ]));
                
                                    $node0->setLeft($node1);
                            $node0->setRight($node36);
                                    $node1->setParent($node0);
                            $node1->setLeft($node2);
                            $node1->setRight($node3);
                                    $node2->setParent($node2);
                                                    $node3->setParent($node1);
                            $node3->setLeft($node4);
                            $node3->setRight($node15);
                                    $node4->setParent($node3);
                            $node4->setLeft($node5);
                            $node4->setRight($node12);
                                    $node5->setParent($node4);
                            $node5->setLeft($node6);
                            $node5->setRight($node11);
                                    $node6->setParent($node5);
                            $node6->setLeft($node7);
                            $node6->setRight($node8);
                                    $node7->setParent($node7);
                                                    $node8->setParent($node6);
                            $node8->setLeft($node9);
                            $node8->setRight($node10);
                                    $node9->setParent($node9);
                                                    $node10->setParent($node10);
                                                    $node11->setParent($node11);
                                                    $node12->setParent($node4);
                            $node12->setLeft($node13);
                            $node12->setRight($node14);
                                    $node13->setParent($node13);
                                                    $node14->setParent($node14);
                                                    $node15->setParent($node3);
                            $node15->setLeft($node16);
                            $node15->setRight($node17);
                                    $node16->setParent($node16);
                                                    $node17->setParent($node15);
                            $node17->setLeft($node18);
                            $node17->setRight($node25);
                                    $node18->setParent($node17);
                            $node18->setLeft($node19);
                            $node18->setRight($node22);
                                    $node19->setParent($node18);
                            $node19->setLeft($node20);
                            $node19->setRight($node21);
                                    $node20->setParent($node20);
                                                    $node21->setParent($node21);
                                                    $node22->setParent($node18);
                            $node22->setLeft($node23);
                            $node22->setRight($node24);
                                    $node23->setParent($node23);
                                                    $node24->setParent($node24);
                                                    $node25->setParent($node17);
                            $node25->setLeft($node26);
                            $node25->setRight($node35);
                                    $node26->setParent($node25);
                            $node26->setLeft($node27);
                            $node26->setRight($node34);
                                    $node27->setParent($node26);
                            $node27->setLeft($node28);
                            $node27->setRight($node33);
                                    $node28->setParent($node27);
                            $node28->setLeft($node29);
                            $node28->setRight($node32);
                                    $node29->setParent($node28);
                            $node29->setLeft($node30);
                            $node29->setRight($node31);
                                    $node30->setParent($node30);
                                                    $node31->setParent($node31);
                                                    $node32->setParent($node32);
                                                    $node33->setParent($node33);
                                                    $node34->setParent($node34);
                                                    $node35->setParent($node35);
                                                    $node36->setParent($node0);
                            $node36->setLeft($node37);
                            $node36->setRight($node38);
                                    $node37->setParent($node37);
                                                    $node38->setParent($node36);
                            $node38->setLeft($node39);
                            $node38->setRight($node42);
                                    $node39->setParent($node38);
                            $node39->setLeft($node40);
                            $node39->setRight($node41);
                                    $node40->setParent($node40);
                                                    $node41->setParent($node41);
                                                    $node42->setParent($node38);
                            $node42->setLeft($node43);
                            $node42->setRight($node44);
                                    $node43->setParent($node43);
                                                    $node44->setParent($node42);
                            $node44->setLeft($node45);
                            $node44->setRight($node48);
                                    $node45->setParent($node44);
                            $node45->setLeft($node46);
                            $node45->setRight($node47);
                                    $node46->setParent($node46);
                                                    $node47->setParent($node47);
                                                    $node48->setParent($node48);
                                
        $this->tree = new Tree($node0);
    }

    /**
    * Process values by tree
    *
    * @param array $values
    *
    * @return array
    */
    public function process(array $values)
    {
        return $this->tree->process($values);
    }
}
